sistema/expedicao/urls.py
from django.urls import path
from . import views



app_name = "expedicao"
urlpatterns = [
    path('', views.ExpedicaoView.as_view(), name='home'),
    path('addexp', views.ExpedicaoEntradaView.as_view(), name='entrada_expedicao')
]

sistema/funcionarios/urls.py
from django.urls import path
from . import views




app_name = "funcionarios"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('addcomp/', views.EntComp.as_view(), name='entrada_comportamento'),
    path('addrend/', views.EntRend.as_view(), name='entrada_rendimento'),
    path('adderro/', views.EntErro.as_view(), name='entrada_erro'),
    path('<str:func_nome>/', views.BasicFuncView.as_view(), name='basic_func'),
    path('<str:func_nome>/comportamento', views.FuncComportamento.as_view(), name='comportamento'),
    path('<str:func_nome>/erros', views.FuncErro.as_view(), name='erros'),
    path('<str:func_nome>/rendimento', views.FuncRendimento.as_view(), name='rendimento')
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout

urlpatterns = [
    path('', login, {'template_name':'funcionarios/login.html'}),
    path('logout', logout, {'template_name':'funcionarios/logout.html'}),
    path('funcionarios/', include('funcionarios.urls')),
    path('expedicao/', include('expedicao.urls')),
    path('anuncios/', include('anuncios.urls')),
    path('admin/', admin.site.urls)
]

sistema/funcionarios/forms.py
from django import forms
from .models import Funcionario, Comportamento, Rendimento, Erros



#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ORDEM_CHOICES = [('Nome','Nome'),('Comportamento','Comportamento'),('Rendimento','Rendimento'),('Erros','Erros')]


class OrderForm(forms.Form):
    ordem = forms.ChoiceField(choices=ORDEM_CHOICES)
    ordem.widget.attrs.update({'class': 'form-control'})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


DIA_CHOICES = [('01','01'),('02','02'),('03','03'),('04','04'),('05','05'),('06','06'),('07','07'),('08','08')
,('09','09'),('10','10'),('11','11'),('12','12'),('13','13'),('14','14'),('15','15'),('16','16'),('17','17'),
('20','20'),('30','30'),('31','31')]
MES_CHOICES = [('01','01'),('02','02'),('03','03'),('04','04'),('05','05'),('06','06'),('07','07'),('08','08'),
('09','09'),('10','10'),('11','11'),('12','12')]
ANO_CHOICES = [('2018','2018'),('2019','2019')]
COMP_CHOICES = [(5,5),(0,0),(1,1),(2,2),(3,3),(4,4),(6,6),(7,7),(8,8),(9,9),(10,10)]


class CompForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.all())
    banco = forms.ChoiceField(choices=COMP_CHOICES)
    ordens = forms.ChoiceField(choices=COMP_CHOICES)
    ajuda = forms.ChoiceField(choices=COMP_CHOICES)
    celular = forms.ChoiceField(choices=COMP_CHOICES)
    pausa_indev = forms.ChoiceField(choices=COMP_CHOICES)
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)


    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})
    banco.widget.attrs.update({'class': 'form-control col-md-5'})
    ordens.widget.attrs.update({'class': 'form-control col-md-5'})
    ajuda.widget.attrs.update({'class': 'form-control col-md-5'})
    celular.widget.attrs.update({'class': 'form-control col-md-5'})
    pausa_indev.widget.attrs.update({'class': 'form-control col-md-5'})

    class Meta:
        model = Comportamento
        fields =  ('funcionario','ordens','ajuda','celular','pausa_indev','dia','mes','ano')




#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class RendForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.filter(tipo=2))
    total_diario = forms.IntegerField()
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)


    total_diario.widget.attrs.update({'class': 'form-control col-md-5'})
    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})


    class Meta:
        model = Rendimento
        fields =  ('funcionario','total_diario','dia','mes','ano')




#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

CONTA_CHOICES = [(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(1,1),(12,12)]
ERRO_CHOICES = [('etiqueta_trocada','Etiqueta trocada'),('falta_produto','Faltando produto'),
    ('produto_trocado','Produto trocado'),('sabor_errado','Sabor Errado'),
    ('produto_vencido','Produto vencido'),('falta_brinde','Faltando brinde')]

class ErroForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.filter(tipo=2))
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)
    dia_pedido = forms.ChoiceField(choices=DIA_CHOICES)
    mes_pedido = forms.ChoiceField(choices=MES_CHOICES)
    ano_pedido = forms.ChoiceField(choices=ANO_CHOICES)
    pedido = forms.CharField(max_length=200)
    cliente = forms.CharField(max_length=200)
    erro = forms.ChoiceField(choices=ERRO_CHOICES)
    conta = forms.ChoiceField(choices=CONTA_CHOICES)

    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})
    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    dia_pedido.widget.attrs.update({'class': 'form-control col-md'})
    mes_pedido.widget.attrs.update({'class': 'form-control col-md'})
    ano_pedido.widget.attrs.update({'class': 'form-control col-md'})
    pedido.widget.attrs.update({'class': 'form-control col-md-5'})
    cliente.widget.attrs.update({'class': 'form-control col-md-5'})
    erro.widget.attrs.update({'class': 'form-control col-md-5'})
    conta.widget.attrs.update({'class': 'form-control col-md-5'})

    class Meta:
        model = Erros
        fields =  ('funcionario','pedido','cliente','erro','conta','dia','mes','ano','dia_pedido','mes_pedido','ano_pedido')

sistema/funcionarios/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.generic import TemplateView
from datetime import datetime

from .models import Funcionario, Comportamento, Erros, Rendimento
from .forms import OrderForm, CompForm, RendForm, ErroForm

# Create your views here.

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class HomeView(TemplateView):
    template_name = 'funcionarios/home.html'

    def get(self, request):
        funcs =  Funcionario.objects.order_by('nome')
        form = OrderForm()
        return render(request, 'funcionarios/home.html', {'funcs': funcs, 'form': form})

    def post(self, request):
        funcs =  Funcionario.objects.order_by('nome')
        form = OrderForm(request.POST)
        if form.is_valid():
            ordem = form.cleaned_data['ordem']
            if ordem == 'Rendimento':
                funcs =  Funcionario.objects.order_by('med_rendimento')
            elif ordem == 'Comportamento':
                funcs =  Funcionario.objects.order_by('med_comportamento')
            elif ordem == 'Erros':
                funcs =  Funcionario.objects.order_by('med_erros')
            else:
                funcs =  Funcionario.objects.order_by('nome')

        return render(request, 'funcionarios/home.html', {'funcs': funcs, 'form': form})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class BasicFuncView(TemplateView):
    template_name = 'funcionarios/basic_func.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        return render(request, 'funcionarios/basic_func.html', {'func': func,'funcs': funcs})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class FuncComportamento(TemplateView):
    template_name = 'funcionarios/comportamento.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Comportamento.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/comportamento.html', {'func': func, 'funcs':funcs, 'tab':tab})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class FuncErro(TemplateView):
    template_name = 'funcionarios/erros.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Rendimento.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/erros.html', {'func': func, 'funcs':funcs, 'tab':tab})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class FuncRendimento(TemplateView):
    template_name = 'funcionarios/rendimento.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Erros.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/rendimento.html', {'func': func, 'funcs':funcs, 'tab':tab})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntComp(TemplateView):
    template_name = 'funcionarios/entrada_comportamento.html'

    def get(self, request):
        form = CompForm()
        return render(request, 'funcionarios/entrada_comportamento.html', {'form': form})

    def post(self, request):
        form = CompForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            post.media = ((post.ordens*2)+(post.banco*3)+(post.celular)+(post.pausa_indev))/7
            post.usuario = request.user
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = CompForm()

        return render(request, 'funcionarios/entrada_comportamento.html', {'form': form})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntRend(TemplateView):
    template_name = 'funcionarios/entrada_rendimento.html'

    def get(self, request):
        form = RendForm()
        return render(request, 'funcionarios/entrada_rendimento.html', {'form': form})

    def post(self, request):
        form = RendForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            post.usuario = request.user
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = RendForm()

        return render(request, 'funcionarios/entrada_rendimento.html', {'form': form})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntErro(TemplateView):
    template_name = 'funcionarios/entrada_erro.html'

    def get(self, request):
        form = ErroForm()
        return render(request, 'funcionarios/entrada_erro.html', {'form': form})

    def post(self, request):
        form = ErroForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            dia_pedido = form.cleaned_data['dia_pedido']
            mes_pedido = form.cleaned_data['mes_pedido']
            ano_pedido = form.cleaned_data['ano_pedido']
            post.usuario = request.user
            post.data_pedido = ano_pedido+'-'+mes_pedido+'-'+dia_pedido
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = ErroForm()

        return render(request, 'funcionarios/entrada_erro.html', {'form': form})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

sistema/funcionarios/templates/funcionarios/basic_func.html
{% extends "header.html" %}

{% block content %}
{% include 'funcionarios/includes/htmlsnippet.html' %}

  <div class="text-center container-fluid">
    <br>
    <div class="container">
      <h1 class="jumbotron-heading">{{func.nome}}</h1>
      <h5 class="jumbotron-heading">Comportamento:</h5>
      <p class="lead text-muted">{{func.med_comportamento}}</p>
      {% if func.tipo == 2 %}
        <div class="row">
          <div class="col">
            <h5 class="jumbotron-heading">Rendimento:</h5>
            <p class="lead text-muted">{{func.med_rendimento}}</p>
            <h5 class="jumbotron-heading">Erros de etiqueta trocada:</h5>
            <p class="lead text-muted">{{func.erro_etiqueta}}</p>
            <h5 class="jumbotron-heading">Erros de falta produto:</h5>
            <p class="lead text-muted">{{func.erro_falta}}</p>
            <h5 class="jumbotron-heading">Erros de produto trocado:</h5>
            <p class="lead text-muted">{{func.erro_troca}}</p>
            <h5 class="jumbotron-heading">Erros de sabor errado:</h5>
            <p class="lead text-muted">{{func.erro_sabor}}</p>
            <h5 class="jumbotron-heading">Erros de produto vencido:</h5>
            <p class="lead text-muted">{{func.erro_vencido}}</p>
            <h5 class="jumbotron-heading">Erros de falta de brinde:</h5>
            <p class="lead text-muted">{{func.erro_brinde}}</p>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

sistema/funcionarios/templates/funcionarios/comportamento.html
{% extends "header.html" %}

{% block content %}
{% include 'funcionarios/includes/htmlsnippet.html' %}
  <div class="col-lg-10 px-3 enois">
    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
      <div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
        <div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0">
        </div>
      </div>
      <div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
        <div style="position:absolute;width:200%;height:200%;left:0; top:0">
        </div>
      </div>
    </div>
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>

        </div>
        {% for entry in tab %}
        <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="549" height="231" style="display: block; width: 549px; height: 231px;">{{entry.ordens}}</canvas>
        {% endfor %}
        <h2>Section title</h2>
        <div class="table-responsive">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th>Data</th>
                <th>Ordens</th>
                <th>Celular</th>
                <th>Pausa Indevida</th>
                <th>Banco</th>
              </tr>
            </thead>
            <tbody>
              {% for colu in tab %}
              <tr>
                <td>{{colu.data}}</td>
                <td>{{colu.ordens}}</td>
                <td>{{colu.celular}}</td>
                <td>{{colu.pausa_indev}}</td>
                <td>{{colu.banco}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      </div>

{% endblock %}

sistema/funcionarios/templates/funcionarios/entrada_comportamento.html
{% extends "header.html" %}


{% block content %}
{% include 'funcionarios/includes/htmlsnippet2.html' %}
<div class="container-fluid">
  <br>
  <h3>Adicionar nova entrada de Comportamento</h3>
  <div class="container-fluid">
    <br>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              {{ form.funcionario.errors }}
              <strong>{{ form.funcionario.label_tag }}</strong>
              <p>{{ form.funcionario }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.banco.errors }}
              <strong>{{ form.banco.label_tag }}</strong>
              <p>{{ form.banco }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.ordens.errors }}
              <strong>{{ form.ordens.label_tag }}</strong>
              <p>{{ form.ordens }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.ajuda.errors }}
              <strong>{{ form.ajuda.label_tag }}</strong>
              <p>{{ form.ajuda }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.celular.errors }}
              <strong>{{ form.celular.label_tag }}</strong>
              <p>{{ form.celular }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.pausa_indev.errors }}
              <strong><label for="{{ form.pausa_indev.id_for_label }}">Pausa indevida:</label></strong>
              <p>{{ form.pausa_indev }}</p>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              <strong><p>Data:</p></strong>
              <table class="table">
                <tbody>
                  <tr>
                    <td><label for="{{ form.dia.id_for_label }}">Dia</label></td>
                    <td><label for="{{ form.mes.id_for_label }}">Mes</label></td>
                    <td><label for="{{ form.ano.id_for_label }}">Ano</label></td>
                  </tr>
                  <tr>
                    <td>{{ form.dia }}</td>
                    <td>{{ form.mes }}</td>
                    <td>{{ form.ano }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <button type="submit" class="btn btn-dark">Salvar</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

sistema/funcionarios/templates/funcionarios/entrada_erro.html
{% extends "header.html" %}

{% block content %}
{% include 'funcionarios/includes/htmlsnippet2.html' %}
<div class="container-fluid">
  <br>
  <h3>Adicionar nova entrada de Erro</h3>
  <div class="container-fluid">

    <br>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              {{ form.funcionario.errors }}
              <strong>{{ form.funcionario.label_tag }}</strong>
              <p>{{ form.funcionario }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.pedido.errors }}
              <strong>{{ form.pedido.label_tag }}</strong>
              <p>{{ form.pedido }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.cliente.errors }}
              <strong>{{ form.cliente.label_tag }}</strong>
              <p>{{ form.cliente }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.erro.errors }}
              <strong>{{ form.erro.label_tag }}</strong>
              <p>{{ form.erro }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.conta.errors }}
              <strong>{{ form.conta.label_tag }}</strong></strong>
              <p>{{ form.conta }}</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="container-fluid">
            <div class="fieldWrapper">
              <strong><p>Data:</p></strong>
              <table class="table">
                <tbody>
                  <tr>
                    <td><label for="{{ form.dia.id_for_label }}">Dia</label></td>
                    <td><label for="{{ form.mes.id_for_label }}">Mes</label></td>
                    <td><label for="{{ form.ano.id_for_label }}">Ano</label></td>
                  </tr>
                  <tr>
                    <td>{{ form.dia }}</td>
                    <td>{{ form.mes }}</td>
                    <td>{{ form.ano }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <div class="fieldWrapper">
              <strong><p>Data Pedido:</p></strong>
              <table class="table">
                <tbody>
                  <tr>
                    <td><label for="{{ form.dia_pedido.id_for_label }}">Dia</label></td>
                    <td><label for="{{ form.mes_pedido.id_for_label }}">Mes</label></td>
                    <td><label for="{{ form.ano_pedido.id_for_label }}">Ano</label></td>
                  </tr>
                  <tr>
                    <td>{{ form.dia_pedido }}</td>
                    <td>{{ form.mes_pedido }}</td>
                    <td>{{ form.ano_pedido }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <button type="submit" class="btn btn-dark">Salvar</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

sistema/funcionarios/templates/funcionarios/entrada_rendimento.html
{% extends "header.html" %}

{% block content %}
{% include 'funcionarios/includes/htmlsnippet2.html' %}
<div class="container-fluid">
  <br>
  <h3>Adicionar nova entrada de Rendimento</h3>
  <div class="container-fluid">

    <br>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              {{ form.funcionario.errors }}
              <strong>{{ form.funcionario.label_tag }}</strong>
              <p>{{ form.funcionario }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.total_diario.errors }}
              <strong>{{ form.total_diario.label_tag }}</strong>
              <p>{{ form.total_diario }}</p>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              <strong><p>Data:</p></strong>
              <table class="table">
                <tbody>
                  <tr>
                    <td><label for="{{ form.dia.id_for_label }}">Dia</label></td>
                    <td><label for="{{ form.mes.id_for_label }}">Mes</label></td>
                    <td><label for="{{ form.ano.id_for_label }}">Ano</label></td>
                  </tr>
                  <tr>
                    <td>{{ form.dia }}</td>
                    <td>{{ form.mes }}</td>
                    <td>{{ form.ano }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <button type="submit" class="btn btn-dark">Salvar</button>
          </div>
        </div>
      </div>
    </form>
  </div>

</div>

{% endblock %}

sistema/funcionarios/templates/funcionarios/entrada_rendimento0.html
{% extends "header.html" %}

{% block content %}
{% include 'funcionarios/includes/htmlsnippet2.html' %}
<div class="container-fluid">
  <br>
  <h3>Adicionar nova entrada de Rendimento</h3>
  <div class="container-fluid">

    <br>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              {{ form.funcionario.errors }}
              {{ form.funcionario.label_tag }}
              <p>{{ form.funcionario }}</p>
            </div>
            <div class="fieldWrapper">
              {{ form.total_diario.errors }}
              {{ form.total_diario.label_tag }}
              <p>{{ form.total_diario }}</p>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="container-fluid">
            <div class="fieldWrapper">
              <p>Data:</p>
              <table class="table">
                <tbody>
                  <tr>
                    <td><label for="{{ form.dia.id_for_label }}">Dia</label></td>
                    <td><label for="{{ form.mes.id_for_label }}">Mes</label></td>
                    <td><label for="{{ form.ano.id_for_label }}">Ano</label></td>
                  </tr>
                  <tr>
                    <td>{{ form.dia }}</td>
                    <td>{{ form.mes }}</td>
                    <td>{{ form.ano }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <br>
            <button type="submit" class="btn btn-dark">Salvar</button>
          </div>
        </div>
      </div>
    </form>
  </div>

</div>

{% endblock %}

sistema/funcionarios/templates/funcionarios/home.html
{% extends "header.html" %}

{% block content %}
<div class="container-fluid">
  <br>
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        {% for func in funcs %}
        <div class="list-group">
          <a href="{% url 'funcionarios:basic_func' func.nome %}" class="list-group-item list-group-item-action">{{func.nome}}</a>
        </div>
        {% endfor %}
      </div>
      <div class="col">
        <div class="form-group container">
          <p><h3>Ordernar por:</h3></p>
          <form method="post">
            {% csrf_token %}
            <p>{{ form.ordem }}</p>
            <button type="submit" class="btn btn-dark">Nova ordem</button>
          </form>
          <br>
        </div>
        <div class="container">
          <p><h3>Adicionar nova entrada:</h3></p>
          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <a class="btn btn-dark" href="{% url 'funcionarios:entrada_comportamento' %}">Comportamento</a>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <a class="btn btn-dark" href="{% url 'funcionarios:entrada_rendimento' %}">Rendimento</a>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <a class="btn btn-dark" href="{% url 'funcionarios:entrada_erro' %}">Erro</a>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="First group">
              <a class="btn btn-dark" href="{% url 'expedicao:entrada_expedicao' %}">Expedicao</a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

</div>

{% endblock %}