sistema/anuncios/urls.py
from django.urls import path
from . import views



app_name = "anuncios"
urlpatterns = [
    path('', views.AnunciosView.as_view(), name='home'),
    path('addanuncio', views.AnunciosEntradaView.as_view(), name='entrada_anuncios')
]

sistema/expedicao/urls.py
from django.urls import path
from . import views



app_name = "expedicao"
urlpatterns = [
    path('', views.ExpedicaoView.as_view(), name='home'),
    path('addexp', views.ExpedicaoEntradaView.as_view(), name='entrada_expedicao')
]

sistema/funcionarios/urls.py
from django.urls import path
from . import views




app_name = "funcionarios"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('addcomp/', views.EntComp.as_view(), name='entrada_comportamento'),
    path('addrend/', views.EntRend.as_view(), name='entrada_rendimento'),
    path('adderro/', views.EntErro.as_view(), name='entrada_erro'),
    path('<str:func_nome>/', views.BasicFuncView.as_view(), name='basic_func'),
    path('<str:func_nome>/comportamento', views.FuncComportamento.as_view(), name='comportamento'),
    path('<str:func_nome>/erros', views.FuncErro.as_view(), name='erros'),
    path('<str:func_nome>/rendimento', views.FuncRendimento.as_view(), name='rendimento')
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout

urlpatterns = [
    path('', login, {'template_name':'funcionarios/login.html'}),
    path('logout', logout, {'template_name':'funcionarios/logout.html'}),
    path('funcionarios/', include('funcionarios.urls')),
    path('expedicao/', include('expedicao.urls')),
    path('anuncios/', include('anuncios.urls')),
    path('admin/', admin.site.urls)
]

sistema/funcionarios/forms.py
from django import forms
from .models import Funcionario, Comportamento, Rendimento, Erros



#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ORDEM_CHOICES = [('Nome','Nome'),('Comportamento','Comportamento'),('Rendimento','Rendimento'),('Erros','Erros')]


class OrderForm(forms.Form):
    ordem = forms.ChoiceField(choices=ORDEM_CHOICES)
    ordem.widget.attrs.update({'class': 'form-control'})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


DIA_CHOICES = [('01','01'),('02','02'),('03','03'),('04','04'),('05','05'),('06','06'),('07','07'),('08','08')
,('09','09'),('10','10'),('11','11'),('12','12'),('13','13'),('14','14'),('15','15'),('16','16'),('17','17'),
('20','20'),('30','30'),('31','31')]
MES_CHOICES = [('01','01'),('02','02'),('03','03'),('04','04'),('05','05'),('06','06'),('07','07'),('08','08'),
('09','09'),('10','10'),('11','11'),('12','12')]
ANO_CHOICES = [('2018','2018'),('2019','2019')]
COMP_CHOICES = [(5,5),(0,0),(1,1),(2,2),(3,3),(4,4),(6,6),(7,7),(8,8),(9,9),(10,10)]


class CompForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.all())
    banco = forms.ChoiceField(choices=COMP_CHOICES)
    ordens = forms.ChoiceField(choices=COMP_CHOICES)
    ajuda = forms.ChoiceField(choices=COMP_CHOICES)
    celular = forms.ChoiceField(choices=COMP_CHOICES)
    pausa_indev = forms.ChoiceField(choices=COMP_CHOICES)
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)


    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})
    banco.widget.attrs.update({'class': 'form-control col-md-5'})
    ordens.widget.attrs.update({'class': 'form-control col-md-5'})
    ajuda.widget.attrs.update({'class': 'form-control col-md-5'})
    celular.widget.attrs.update({'class': 'form-control col-md-5'})
    pausa_indev.widget.attrs.update({'class': 'form-control col-md-5'})

    class Meta:
        model = Comportamento
        fields =  ('funcionario','ordens','ajuda','celular','pausa_indev','dia','mes','ano')




#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class RendForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.filter(tipo=2))
    total_diario = forms.IntegerField()
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)


    total_diario.widget.attrs.update({'class': 'form-control col-md-5'})
    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})


    class Meta:
        model = Rendimento
        fields =  ('funcionario','total_diario','dia','mes','ano')




#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

CONTA_CHOICES = [(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(1,1),(12,12)]
ERRO_CHOICES = [('etiqueta_trocada','Etiqueta trocada'),('falta_produto','Faltando produto'),
    ('produto_trocado','Produto trocado'),('sabor_errado','Sabor Errado'),
    ('produto_vencido','Produto vencido'),('falta_brinde','Faltando brinde')]

class ErroForm(forms.ModelForm):
    funcionario = forms.ModelChoiceField(Funcionario.objects.filter(tipo=2))
    dia = forms.ChoiceField(choices=DIA_CHOICES)
    mes = forms.ChoiceField(choices=MES_CHOICES)
    ano = forms.ChoiceField(choices=ANO_CHOICES)
    dia_pedido = forms.ChoiceField(choices=DIA_CHOICES)
    mes_pedido = forms.ChoiceField(choices=MES_CHOICES)
    ano_pedido = forms.ChoiceField(choices=ANO_CHOICES)
    pedido = forms.CharField(max_length=200)
    cliente = forms.CharField(max_length=200)
    erro = forms.ChoiceField(choices=ERRO_CHOICES)
    conta = forms.ChoiceField(choices=CONTA_CHOICES)

    funcionario.widget.attrs.update({'class': 'form-control col-md-5'})
    dia.widget.attrs.update({'class': 'form-control col-md'})
    mes.widget.attrs.update({'class': 'form-control col-md'})
    ano.widget.attrs.update({'class': 'form-control col-md'})
    dia_pedido.widget.attrs.update({'class': 'form-control col-md'})
    mes_pedido.widget.attrs.update({'class': 'form-control col-md'})
    ano_pedido.widget.attrs.update({'class': 'form-control col-md'})
    pedido.widget.attrs.update({'class': 'form-control col-md-5'})
    cliente.widget.attrs.update({'class': 'form-control col-md-5'})
    erro.widget.attrs.update({'class': 'form-control col-md-5'})
    conta.widget.attrs.update({'class': 'form-control col-md-5'})

    class Meta:
        model = Erros
        fields =  ('funcionario','pedido','cliente','erro','conta','dia','mes','ano','dia_pedido','mes_pedido','ano_pedido')

sistema/funcionarios/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.views.generic import TemplateView
from datetime import datetime

from .models import Funcionario, Comportamento, Erros, Rendimento
from .forms import OrderForm, CompForm, RendForm, ErroForm

# Create your views here.

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class HomeView(TemplateView):
    template_name = 'funcionarios/home.html'

    def get(self, request):
        funcs =  Funcionario.objects.order_by('nome')
        form = OrderForm()
        return render(request, 'funcionarios/home.html', {'funcs': funcs, 'form': form})

    def post(self, request):
        funcs =  Funcionario.objects.order_by('nome')
        form = OrderForm(request.POST)
        if form.is_valid():
            ordem = form.cleaned_data['ordem']
            if ordem == 'Rendimento':
                funcs =  Funcionario.objects.order_by('med_rendimento')
            elif ordem == 'Comportamento':
                funcs =  Funcionario.objects.order_by('med_comportamento')
            elif ordem == 'Erros':
                funcs =  Funcionario.objects.order_by('med_erros')
            else:
                funcs =  Funcionario.objects.order_by('nome')

        return render(request, 'funcionarios/home.html', {'funcs': funcs, 'form': form})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class BasicFuncView(TemplateView):
    template_name = 'funcionarios/basic_func.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        return render(request, 'funcionarios/basic_func.html', {'func': func,'funcs': funcs})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class FuncComportamento(TemplateView):
    template_name = 'funcionarios/comportamento.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Comportamento.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/comportamento.html', {'func': func, 'funcs':funcs, 'tab':tab})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class FuncErro(TemplateView):
    template_name = 'funcionarios/erros.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Rendimento.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/erros.html', {'func': func, 'funcs':funcs, 'tab':tab})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class FuncRendimento(TemplateView):
    template_name = 'funcionarios/rendimento.html'

    def get(self, request, func_nome):
        func = get_object_or_404(Funcionario, nome=func_nome)
        funcs =  Funcionario.objects.order_by('nome').exclude(nome=func_nome)
        try:
            tab = Erros.objects.filter(funcionario=func.id)
        except:
            tab = 'Nenhuma entrada encontrada.'

        return render(request, 'funcionarios/rendimento.html', {'func': func, 'funcs':funcs, 'tab':tab})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntComp(TemplateView):
    template_name = 'funcionarios/entrada_comportamento.html'

    def get(self, request):
        form = CompForm()
        return render(request, 'funcionarios/entrada_comportamento.html', {'form': form})

    def post(self, request):
        form = CompForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            post.media = ((post.ordens*2)+(post.banco*3)+(post.celular)+(post.pausa_indev))/7
            post.usuario = request.user
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = CompForm()

        return render(request, 'funcionarios/entrada_comportamento.html', {'form': form})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntRend(TemplateView):
    template_name = 'funcionarios/entrada_rendimento.html'

    def get(self, request):
        form = RendForm()
        return render(request, 'funcionarios/entrada_rendimento.html', {'form': form})

    def post(self, request):
        form = RendForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            post.usuario = request.user
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = RendForm()

        return render(request, 'funcionarios/entrada_rendimento.html', {'form': form})


#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class EntErro(TemplateView):
    template_name = 'funcionarios/entrada_erro.html'

    def get(self, request):
        form = ErroForm()
        return render(request, 'funcionarios/entrada_erro.html', {'form': form})

    def post(self, request):
        form = ErroForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            dia = form.cleaned_data['dia']
            mes = form.cleaned_data['mes']
            ano = form.cleaned_data['ano']
            dia_pedido = form.cleaned_data['dia_pedido']
            mes_pedido = form.cleaned_data['mes_pedido']
            ano_pedido = form.cleaned_data['ano_pedido']
            post.usuario = request.user
            post.data_pedido = ano_pedido+'-'+mes_pedido+'-'+dia_pedido
            post.data = ano+'-'+mes+'-'+dia
            post.save()
            form = ErroForm()

        return render(request, 'funcionarios/entrada_erro.html', {'form': form})

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

sistema/funcionarios/templates/header.html
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Supervisão</title>

    <!-- Bootstrap core CSS -->
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'funcionarios/css/bootstrap.css' %}" type = "text/css"/>

    <style type="text/css">
  		html,
  		body {
  		  height:100%;
          background-color: #fffcfc;
  		}
  	</style>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'funcionarios:home' %}"><strong>Supervisão</strong></a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'funcionarios:home' %}">Funcionarios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'expedicao:home' %}">Expedicao</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'anuncios:home' %}">Anuncios</a>
          </li>
        </ul>
      </div>
      <div class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </div>
      {% else %}
      <a class="navbar-brand" href="/">Supervisão</a>
      {% endif %}

    </nav>

    {% if user.is_authenticated %}
			   {% block content %}
			   {% endblock %}
    {% else %}
      <div class="container-fluid">
        <div class="container">
        <br>
        <h3>Faça Login</h3>
            </div>
      </div>

    {% endif %}
    <br>
    <br>
    <br>
    <br><br>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

sistema/funcionarios/templates/headerlogin.html
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Supervisão</title>

    <!-- Bootstrap core CSS -->
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'funcionarios/css/bootstrap.css' %}" type = "text/css"/>

    <style type="text/css">
  		html,
  		body {
  		  height:100%;
          background-color: #fffcfc;
  		}
  	</style>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'funcionarios:home' %}"><strong>Supervisão</strong></a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'funcionarios:home' %}">Funcionarios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'expedicao:home' %}">Expedicao</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'anuncios:home' %}">Anuncios</a>
          </li>
        </ul>
      </div>
      <div class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </div>
      {% else %}
      <a class="navbar-brand" href="/">Supervisão</a>
      {% endif %}

    </nav>


			   {% block content %}
			   {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>